PlanilhaEletronicaWeb/Controllers/ListaReceitaController.cs
using PlanilhaEletronicaWeb.Models;
using PlanilhaEletronicaWeb.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PlanilhaEletronicaWeb.Controllers
{
    public class ListaReceitaController : Controller
    {
		private PlanilhaEletronicaWebContext db = new PlanilhaEletronicaWebContext();

        // GET: ListaReceita
        public ActionResult Index(string idTipoReceita, string Filtrar)
        {
			if (String.IsNullOrEmpty(idTipoReceita))
			{
				idTipoReceita = "0";
			}
			int IdReceita = int.Parse(idTipoReceita);
			var query = from tr in db.Receitas
						where tr.IdTipoReceita == IdReceita
						select new { tr.IdTipoReceita, tr.Situacao };

			var tipoReceita = new List<Receita>();

			if (Filtrar != null)
			{
				foreach (var item in query)
				{
					Receita listReceita = new Receita();
					listReceita.IdTipoReceita = item.IdTipoReceita;
					listReceita.Situacao = item.Situacao;
					tipoReceita.Add(listReceita);
				}
			}
			ViewBag.IdTipoReceita = new SelectList(db.Receitas, "IdTipoReceita", "IdTipoReceita");
			ViewBag.Situacao = new SelectList(db.Receitas, "Situacao", "Situacao");

			ViewBag.Lista = tipoReceita.ToList();
			return View();
        }
    }
}

PlanilhaEletronicaWeb/Controllers/TipoDespesaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlanilhaEletronicaWeb.Models;
using PlanilhaEletronicaWeb.Models.Classes;

namespace PlanilhaEletronicaWeb.Controllers
{
    public class TipoDespesaController : Controller
    {
        private PlanilhaEletronicaWebContext db = new PlanilhaEletronicaWebContext();

        // GET: TipoDespesa
        public ActionResult Index(String busca)
        {
			if (String.IsNullOrEmpty(busca))
			{
				return View(db.TipoDespesas.ToList());
			}

			var result = db.TipoDespesas.Where(tipo => tipo.Despesa.ToLower().Contains(busca) && tipo.Situacao == true);
			return View(result.ToList());
		}

        // GET: TipoDespesa/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoDespesa tipoDespesa = db.TipoDespesas.Find(id);
            if (tipoDespesa == null)
            {
                return HttpNotFound();
            }
            return View(tipoDespesa);
        }

        // GET: TipoDespesa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoDespesa/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "IdTipoDespesa,Despesa,Situacao,Caracteristica")] TipoDespesa tipoDespesa)
        {
            if (ModelState.IsValid)
            {
                db.TipoDespesas.Add(tipoDespesa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoDespesa);
        }

        // GET: TipoDespesa/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoDespesa tipoDespesa = db.TipoDespesas.Find(id);
            if (tipoDespesa == null)
            {
                return HttpNotFound();
            }
            return View(tipoDespesa);
        }

        // POST: TipoDespesa/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "IdTipoDespesa,Despesa,Situacao,Caracteristica")] TipoDespesa tipoDespesa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoDespesa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoDespesa);
        }

        // GET: TipoDespesa/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoDespesa tipoDespesa = db.TipoDespesas.Find(id);
            if (tipoDespesa == null)
            {
                return HttpNotFound();
            }
            return View(tipoDespesa);
        }

        // POST: TipoDespesa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoDespesa tipoDespesa = db.TipoDespesas.Find(id);
			db.Entry(tipoDespesa).State = EntityState.Modified;
			//db.TipoDespesas.Remove(tipoDespesa);
			tipoDespesa.Situacao = false;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlanilhaEletronicaWeb/Controllers/TipoReceitaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PlanilhaEletronicaWeb.Models;
using PlanilhaEletronicaWeb.Models.Classes;

namespace PlanilhaEletronicaWeb.Controllers
{
    public class TipoReceitaController : Controller
    {
        private PlanilhaEletronicaWebContext db = new PlanilhaEletronicaWebContext();

        // GET: TipoReceita
        public ActionResult Index()
        {
            return View(db.TipoReceitas.ToList());
        }

        // GET: TipoReceita/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoReceita tipoReceita = db.TipoReceitas.Find(id);
            if (tipoReceita == null)
            {
                return HttpNotFound();
            }
            return View(tipoReceita);
        }

        // GET: TipoReceita/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: TipoReceita/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Nome")] TipoReceita tipoReceita)
        {
            if (ModelState.IsValid)
            {
                db.TipoReceitas.Add(tipoReceita);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tipoReceita);
        }

        // GET: TipoReceita/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoReceita tipoReceita = db.TipoReceitas.Find(id);
            if (tipoReceita == null)
            {
                return HttpNotFound();
            }
            return View(tipoReceita);
        }

        // POST: TipoReceita/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Nome")] TipoReceita tipoReceita)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tipoReceita).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tipoReceita);
        }

        // GET: TipoReceita/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            TipoReceita tipoReceita = db.TipoReceitas.Find(id);
            if (tipoReceita == null)
            {
                return HttpNotFound();
            }
            return View(tipoReceita);
        }

        // POST: TipoReceita/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            TipoReceita tipoReceita = db.TipoReceitas.Find(id);
            db.TipoReceitas.Remove(tipoReceita);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PlanilhaEletronicaWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Planilha Eletronica", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Cliente", "Index", "Cliente")</li>
                    <li>@Html.ActionLink("Categoria", "Index", "Categoria")</li>
                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Despesas <span class="caret"></span>
                        </a>
                        <ul class="nav dropdown-menu">
                            <li>@Html.ActionLink("Tipo Despesa", "Index", "TipoDespesa")</li>
                            <li>@Html.ActionLink("Despesa", "Index", "Despesa")</li>
                        </ul>
                    </li>

                    <li>
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                            Receitas <span class="caret"></span>
                        </a>
                        <ul class="nav dropdown-menu">
                            <li>@Html.ActionLink("Tipo Receita", "Index", "TipoReceita")</li>
                            <li>@Html.ActionLink("Receita", "Index", "Receita")</li>
                            <li>@Html.ActionLink("Lista Receita", "Index", "ListaReceita")</li>
                        </ul>
                    
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>